#!/bin/bash

################################################################################
## fix sources list
################################################################################

# grab source.lists file
logger -t late-command "getting original sources.list"
wget -q https://raw.githubusercontent.com/morph027/preseed-linuxmint/blob/xenial/sources.list -O /etc/apt/sources.list

# add extras.ubuntu.com gpg key
logger -t late-command "getting key 16126D3A3E5C1192"
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 16126D3A3E5C1192
# refresh package lists
logger -t late-command "refresh package lists"
apt-get update

################################################################################
## fix network-manager
################################################################################

logger -t late-command "fixing network-manager"

cat > /etc/network/interfaces << EOF
# interfaces(5) file used by ifup(8) and ifdown(8)
auto lo
iface lo inet loopback

EOF

################################################################################
## fix shutdown menu
################################################################################

logger -t late-command "fixing shutdown menu"

cat > /usr/share/glib-2.0/schemas/org.cinnamon.desktop.session.gschema.override << EOF
[org.cinnamon.desktop.session]
settings-daemon-uses-logind=true
session-manager-uses-logind=true
screensaver-uses-logind=false
EOF

glib-compile-schemas /usr/share/glib-2.0/schemas

################################################################################
## set cinnamon as default session
################################################################################

logger -t late-command "make cinnamon default"

cat > /usr/share/lightdm/lightdm.conf.d/50-cinnamon.conf << EOF
[SeatDefaults]
user-session=cinnamon
EOF

################################################################################
## set nemo as default filebrowser
################################################################################

logger -t late-command "make nemo default"

mkdir -p /etc/skel/.local/share
cat > /etc/skel/.local/share/applications << EOF

[Default Applications]
inode/directory=nemo.desktop
application/x-gnome-saved-search=nemo.desktop
EOF

logger -t late-command "remove nautilus"

apt-get purge nautilus -y

################################################################################
## dconf settings
################################################################################

# enable custom presets

mkdir -p /etc/dconf/profile/
cat > /etc/dconf/profile/user << EOF
user-db:user
system-db:local
EOF

# fonts

mkdir -p /etc/dconf/db/local.d
cat > /etc/dconf/db/local.d/01-fonts << EOF
[org/cinnamon/desktop/interface]
font-name='Noto Sans 9'

[org/cinnamon/desktop/wm/preferences]
titlebar-font='Noto Sans Bold 10'

[org/gnome/desktop/interface]
document-font-name='Noto Sans 10'

[org/nemo/desktop]
font='Noto Sans 10'
EOF

# trayicon for language

cat > /etc/dconf/db/local.d/01-ibus-indicator << EOF
[desktop/ibus/panel]
show-icon-on-systray=false

[org/gnome/libgnomekbd/keyboard]
layouts=['de', 'us\talt-intl']
EOF

# finally apply

dconf update

################################################################################
## install additional packages
################################################################################

logger -t late-command "installing additional packages"

################################################################################
## install LTSEnablementStack
## https://wiki.ubuntu.com/Kernel/LTSEnablementStack
################################################################################

#logger -t late-command "installing lts stack"

#apt-get install --install-recommends -y \
#linux-generic-lts-$LTS \
#xserver-xorg-core-lts-$LTS \
#xserver-xorg-lts-$LTS \
#xserver-xorg-video-all-lts-$LTS \
#xserver-xorg-input-all-lts-$LTS \
#libwayland-egl1-mesa-lts-$LTS 

################################################################################
## cleanup
################################################################################

logger -t late-command "cleanup"

apt-get autoremove -y
apt-get clean

################################################################################
## tweaks
################################################################################

## bashrc

# color prompt
sed -i 's,^#force_color_prompt,force_color_prompt,' /etc/skel/.bashrc /home/it/.bashrc
# add to root user, red prompt
sed 's,01;32m,01;31m,' /etc/skel/.bashrc > /root/.bashrc

################################################################################
## user settings
################################################################################
